
class fire_spawner : screen_entity
{
override screen_entity init(staticeventhandler owner, vector2 pos, int spawn_layer)
{
    ticker = owner;
    layer_number = spawn_layer;
    init_defaults(pos);
    return self;
}

screen_entity fire;
override void entity_logic_tick()
{
    if(tics >= random(3, 5) )
    {
        fire = screen_animator(ticker).create_new_enity("burning_flame", (screen_pos + (100, -80) ) );
        fire.velocity = (10 + frandom(-1, 1), -8 + frandom(-1, 1));

        fire = screen_animator(ticker).create_new_enity("burning_flame", (screen_pos + (-100, -100)));
        fire.velocity = (-10 + frandom(-1, 1), -10 + frandom(-1, 1));

        fire = screen_animator(ticker).create_new_enity("burning_flame", (screen_pos + (0, 100)));
        fire.velocity = (0 + frandom(-1, 1), 10 + frandom(-1, 1));

        tics = 0;
    }

    tics++;
}

}

class burning_flame : screen_entity
{
override screen_entity init(staticeventhandler owner, vector2 pos)
{
    init_defaults();

    screen_pos = pos;
    alpha = frandom(0.5, 0.9);
    entity_flag |= SEF_ISTEXTURE;


    velocity = (random(-10, 10), random(-10, 10) );
    console.printf("pos is %f %f", screen_pos.x, screen_pos.y);
    return self;
}

}